Repository AtaraxiaSpaceFoundation/Europa-Station-14, pull requests merged in 2025-09, with the labels that each got.

#75 [Fix] Wall Sprites
  Resources/Textures/Structures/Doors/secret_door.rsi/assembly.png
  Resources/Textures/Structures/Doors/secret_door.rsi/closed.png
  Resources/Textures/Structures/Doors/secret_door.rsi/closing.png
  Resources/Textures/Structures/Doors/secret_door.rsi/open.png
  Resources/Textures/Structures/Doors/secret_door.rsi/opening.png
  Resources/Textures/Structures/Walls/solid_rust.rsi/rgeneric.png
Labels: Изменения: Нет C#, S: Неотсортированный, Изменения: Спрайты

#79 [Tweak] Remove Raznoe Govno
  Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
  Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
  Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
  Resources/Prototypes/Entities/Clothing/Neck/pins.yml
  Resources/Prototypes/Entities/Clothing/Neck/scarfs.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/vending.yml
  Resources/Prototypes/Entities/Objects/Misc/handy_flags.yml
  Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/flags.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/_Europa/Catalog/VendingMachines/Inventories/CaptainDrobeInventory.yml
  Resources/Prototypes/_Europa/Entities/Structures/Specific/Anomaly/anomalies.yml
  Resources/Prototypes/_Goobstation/GameRules/events.yml
  Resources/Prototypes/_Goobstation/Voice/speech_emotes.yml
  Resources/Textures/_Europa/Structures/Specific/Anomalies/wormhole.rsi/meta.json
  Resources/Textures/_Europa/Structures/Specific/Anomalies/wormhole.rsi/wormhole.png
  Resources/migration.yml
Labels: Изменения: Нет C#, S: Неотсортированный, Изменения: Спрайты

#85 [Fix] Holy Shit Pack
  Content.Client/Audio/ContentAudioSystem.cs
  Content.Client/Options/UI/Tabs/AudioTab.xaml
  Content.Client/Options/UI/Tabs/AudioTab.xaml.cs
  Content.Goobstation.Client/Entry/EntryPoint.cs
  Content.Goobstation.Client/IoC/ContentGoobClientIoC.cs
  Content.Goobstation.Client/Voice/IVoiceChatManager.cs
  Content.Goobstation.Client/Voice/VoiceChatClientManager.cs
  Content.Goobstation.Client/Voice/VoiceStreamManager.cs
  Content.Goobstation.Common/CCVar/CCVars.Goob.cs
  Content.Goobstation.Server/Content.Goobstation.Server.csproj
  Content.Goobstation.Server/Entry/EntryPoint.cs
  Content.Goobstation.Server/IoC/ServerGoobContentIoC.cs
  Content.Goobstation.Server/Voice/IVoiceChatServerManager.cs
  Content.Goobstation.Server/Voice/VoiceChatServerManager.cs
  Content.Goobstation.Server/Voice/VoiceChatSystem.cs
  Content.Goobstation.Shared/Voice/VoiceChatNetMessage.cs
  Content.Server/Medical/CrewMonitoring/CrewMonitoringConsoleSystem.cs
  Content.Server/_Europa/Morph/MorphSystem.cs
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Content.Shared/_Europa/Morph/MorphComponent.cs
  Content.Shared/_Europa/Morph/SharedMorphSystem.cs
  Directory.Packages.props
  Resources/Locale/en-US/_Goobstation/voice.ftl
  Resources/Locale/ru-RU/datasets/names/scurret_first.ftl
  Resources/Locale/ru-RU/datasets/names/scurret_last.ftl
  Resources/Prototypes/_RMC14/Entities/Structures/Xeno/xeno_doors.yml
  Resources/Prototypes/_White/Actions/xenomorph.yml
  Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/drone.yml
  Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/maid.yml
  Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/praetorian.yml
  Resources/Prototypes/_White/Entities/Mobs/Xenomorphs/queen.yml
  Resources/Prototypes/_White/Entities/Structures/Doors/resin.yml
  Resources/Prototypes/_White/Entities/Structures/Furniture/resin_nest.yml
  Resources/Prototypes/_White/Entities/Structures/Windows/resin.yml
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Glass/uranium.rsi/bolted_open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Glass/uranium.rsi/emergency_open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Glass/uranium.rsi/meta.json
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Glass/uranium.rsi/open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Glass/uranium.rsi/panel_closed.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Standard/uranium.rsi/bolted_open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Standard/uranium.rsi/emergency_open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Standard/uranium.rsi/meta.json
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Standard/uranium.rsi/open_unlit.png
  Resources/Textures/_Goobstation/Wizard/Structures/Airlocks/Standard/uranium.rsi/panel_closed.png
  Resources/migration.yml
Labels: Изменения: Локализация, Изменения: Спрайты, Изменения: Интерфейс

#106 [Fix] Uhhh Edits
  Content.Server/AlertLevel/AlertLevelSystem.cs
  Resources/Locale/en-US/_europa/chat/managers/chat-manager.ftl
  Resources/Locale/ru-RU/_Goobstation/servercurrency/server_currency.ftl
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
  Resources/Prototypes/Entities/Structures/Windows/mining.yml
  Resources/Prototypes/Entities/Structures/Windows/plasma.yml
  Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
  Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
  Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
  Resources/Prototypes/Entities/Structures/Windows/uranium.yml
  Resources/Prototypes/Entities/Structures/Windows/window.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Prototypes/Guidebook/security.yml
  Resources/Prototypes/Guidebook/station.yml
  Resources/Prototypes/_Europa/Catalog/Fills/Backpacks/backpack.yml
  Resources/Prototypes/_Europa/Catalog/selectable_sets.yml
  Resources/Prototypes/_Europa/Entities/Mobs/NPCs/cortical_borer.yml
  Resources/Prototypes/_Goobstation/Guidebook/rules.yml
  Resources/Prototypes/_Goobstation/Guidebook/sop.yml
  Resources/Prototypes/_Goobstation/radio_channels.yml
  Resources/Prototypes/radio_channels.yml
Labels: Изменения: Локализация, Изменения: Нет C#, S: Неотсортированный

#115 [Tweak] Cortical Borer Things
  Content.Server/_Europa/CorticalBorer/CorticalBorerSystem.Abilities.cs
  Content.Server/_Europa/CorticalBorer/CorticalBorerSystem.cs
  Content.Shared/_Europa/CorticalBorer/CorticalBorer.Actions.cs
  Content.Shared/_Europa/CorticalBorer/SharedCorticalBorerSystem.cs
  Resources/Prototypes/_Europa/Actions/cortical_borer.yml
  Resources/Prototypes/_Europa/Entities/Mobs/NPCs/cortical_borer.yml
Labels: S: Неотсортированный

#116 [Tweak] Remove Mail Time Penalty
  Content.Server/Nyanotrasen/Mail/MailSystem.cs
Labels: S: Неотсортированный

#117 [Port] Smooth Light
  Content.Shared/CombatMode/CombatModeComponent.cs
  Content.Shared/CombatMode/SharedCombatModeSystem.cs
Labels: S: Неотсортированный

#118 [Tweak] Fuck Slippery Curse
  Resources/Prototypes/Entities/Effects/chemistry_effects.yml
  Resources/Prototypes/Entities/Effects/puddle.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/Reagents/Consumable/Drink/base_drink.yml
  Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
  Resources/Prototypes/Reagents/biological.yml
  Resources/Prototypes/Reagents/fun.yml
Labels: Изменения: Нет C#, S: Неотсортированный

#121 [Tweak] Ghost UI Update
  Content.Client/UserInterface/Systems/Ghost/Controls/GhostTargetWindow.xaml
  Content.Client/UserInterface/Systems/Ghost/Controls/GhostTargetWindow.xaml.cs
  Content.Server/Ghost/GhostSystem.cs
  Resources/Locale/en-US/_europa/user-interface/ghostTeleportMenu.ftl
  Resources/Locale/ru-RU/_europa/user-interface/ghostTeleportMenu.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/_Europa/Antag/globalAntagonists.yml
  Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
  Resources/Prototypes/_Goobstation/SlaughterDemon/Mobs/NPC/polymorph.yml
  Resources/Prototypes/_Shitmed/GameRules/events.yml
Labels: Изменения: Локализация, Изменения: Интерфейс

#122 [Tweak] One More Anti-Grief Morph
  Resources/Prototypes/_Europa/Entities/Mobs/Player/morph.yml
Labels: Изменения: Нет C#

#123 [Tweak] InteQ Things
  Resources/Locale/en-US/_europa/job/job-names.ftl
  Resources/Locale/ru-RU/_europa/job/job-names.ftl
  Resources/Prototypes/_Europa/Entities/Mobs/NPCs/inteq.yml
  Resources/Prototypes/_Europa/Entities/Mobs/Player/Other/inteq.yml
  Resources/Prototypes/_Europa/Roles/Jobs/Fun/inteq.yml
  Resources/Prototypes/_Europa/Roles/play_time_trackers.yml
Labels: Изменения: Локализация, Изменения: Нет C#, S: Неотсортированный

#124 [Feature] Aspid Station
  Resources/Maps/_Europa/aspid.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/aspid.yml
Labels: S: Требуется ревью, Изменения: Нет C#, S: Неотсортированный, Изменения: Карты

#127 [Port] ZPass
  Content.Client/Lobby/UI/LobbyGui.xaml
  Content.Client/_Europa/UserInterface/Buttons/ViewPremiumInfoButton.cs
  Content.Client/_Europa/UserInterface/Windows/PremiumPassWindow.xaml
  Content.Client/_Europa/UserInterface/Windows/PremiumPassWindow.xaml.cs
  Resources/Textures/_Europa/Interface/pass.png
  Resources/Textures/_Europa/cat-spoon-coder.png
Labels: S: Неотсортированный, Изменения: Интерфейс
